EXTERNAL_SERVER_IP = "127.0.0.1"
IMAGE_NAME = "fur_fighters_server"
CONTAINER_NAME_MASK = "Fur_lobby_"
EXECUTABLE_FILE_PATH = "./Fur-Fighters_Frenzy_Server.x86_64"
START_PORT = 7770
INTERNAL_PORT = 8687
CONTAINERS_COUNT = 1
